import jsPDF from 'jspdf'
import {
  BasePdfGenerator,
  formatDateTime,
  MARGINS,
  PdfDocumentBuilder,
} from '@deliveroo/pdf-core'
import { Document } from '../../model/documents'

export interface PDFOptions {
  includeWatermark?: boolean
  includeFooter?: boolean
}

const DOCUMENT_TYPE_LABELS: Record<Document['type'], string> = {
  contract: 'Contract',
  invoice: 'Invoice',
  registration: 'Vehicle Registration',
  insurance: 'Insurance Policy',
  inspection: 'Technical Inspection Certificate',
  'tir-carnet': 'TIR Carnet',
  adr: 'ADR Certificate',
  'hazmat-permit': 'Hazmat Transport Permit',
  license: 'License',
  certificate: 'Certificate',
  other: 'Document',
}

const ENTITY_TYPE_LABELS: Record<Document['entityType'], string> = {
  vehicle: 'Vehicle',
  customer: 'Customer',
  supplier: 'Supplier',
  driver: 'Driver',
  company: 'Company',
  other: 'Other',
}

class DocumentPdfGenerator extends BasePdfGenerator<Document> {
  protected override companyName = 'Deliveroo TMS Sp. z o.o.'

  protected getTitle(data: Document): string {
    return DOCUMENT_TYPE_LABELS[data.type]
  }

  protected getFilename(data: Document): string {
    return `${data.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${data.id}.pdf`
  }

  protected override getContentStartY(): number {
    return 40
  }

  protected override async renderHeader(
    doc: jsPDF,
    logoDataUrl: string | null,
    data: Document,
  ): Promise<void> {
    const pageWidth = doc.internal.pageSize.getWidth()

    if (logoDataUrl) {
      doc.addImage(logoDataUrl, 'PNG', 20, 10, 40, 15)
    }

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(0, 0, 0)
    doc.text('Transport Management System', pageWidth - 20 - 60, 15)
    doc.text(this.companyName, pageWidth - 20 - 60, 22)

    doc.setLineWidth(0.5)
    doc.line(MARGINS.left, 30, pageWidth - MARGINS.right, 30)

    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text(this.getTitle(data), MARGINS.left, 40)
  }

  protected override renderFooter(doc: jsPDF): void {
    if (this.options.includeFooter === false) {
      return
    }

    const pageHeight = doc.internal.pageSize.height
    const pageWidth = doc.internal.pageSize.getWidth()
    const footerY = pageHeight - 20

    doc.setLineWidth(0.5)
    doc.line(MARGINS.left, footerY - 5, pageWidth - MARGINS.right, footerY - 5)

    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(0, 0, 0)
    doc.text('Generated by Deliveroo TMS', MARGINS.left, footerY)
    doc.text(`Generated on: ${formatDateTime(new Date())}`, pageWidth - 20 - 50, footerY)

    const pageCount = doc.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2 - 10, footerY)
    }
  }

  protected renderSections(builder: PdfDocumentBuilder, document: Document): void {
    builder
      .sectionPlain('Document Information')
      .fieldPair('Document Name:', document.name)
      .fieldPair('Document Type:', DOCUMENT_TYPE_LABELS[document.type])
      .fieldPair('Document ID:', document.id)

    if (document.number) {
      builder.fieldPair('Document Number:', document.number)
    }

    builder
      .spacer(5)
      .sectionPlain('Related Entity')
      .fieldPair('Related To:', ENTITY_TYPE_LABELS[document.entityType])
      .fieldPair('Entity Name:', document.entityName)
      .fieldPair('Entity ID:', document.entityId)
      .spacer(5)
      .sectionPlain('Important Dates')
      .fieldPair('Issue Date:', formatDateTime(document.issueDate))

    if (document.expiryDate) {
      builder.fieldPair('Expiry Date:', formatDateTime(document.expiryDate))
    }

    builder
      .fieldPair('Created:', formatDateTime(document.createdAt))
      .fieldPair('Last Updated:', formatDateTime(document.updatedAt))

    if (document.issuingAuthority) {
      builder
        .spacer(5)
        .sectionPlain('Issuing Authority')
        .fieldPair('Authority:', document.issuingAuthority)
    }

    if (document.notes) {
      builder.sectionPlain('Notes').fieldMultiline('', document.notes, builder.getPageWidth() - 2 * MARGINS.left)
      builder.spacer(5)
    }

    builder
      .sectionPlain('Document Content')
      .rawText('This is a sample document generated by the Deliveroo TMS system.')
      .rawText('This document contains all the relevant information as stored in the system.')
  }
}

const documentPdfGenerator = new DocumentPdfGenerator()

export async function generateDocumentPDF(
  document: Document,
  options: PDFOptions = {},
): Promise<void> {
  return documentPdfGenerator.generate(document, options)
}

export async function generateDocumentPDFBlob(
  document: Document,
  options: PDFOptions = {},
): Promise<Blob> {
  return documentPdfGenerator.toBlob(document, options)
}
